token.expiration_time: 86400
token.secret: senhanova
login.url.path: /users/login

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
